#!/bin/bash

/etc/init.d/networking restart
ifconfig eth0 up
ifconfig eth0 172.16."$1"1.1/24
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo
ifconfig
echo
